version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auction-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AUCTION_DURATION_MINUTES=1
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo-data:
